"""Initial schema

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_id'), 'instruments', ['id'], unique=False)
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_index(op.f('ix_prices_timestamp'), 'prices', ['timestamp'], unique=False)
    op.create_index('ix_prices_instrument_timestamp', 'prices', ['instrument_id', 'timestamp'], unique=False)
    
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('fees', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('trade_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_index(op.f('ix_trades_account_id'), 'trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_timestamp'), 'trades', ['timestamp'], unique=False)
    
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('average_cost', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('market_value', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_account_id'), 'positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index('ix_positions_account_instrument', 'positions', ['account_id', 'instrument_id'], unique=True)
    
    op.create_table('pnl_timeseries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('unrealized_pnl', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('total_pnl', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('portfolio_value', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pnl_timeseries_account_id'), 'pnl_timeseries', ['account_id'], unique=False)
    op.create_index(op.f('ix_pnl_timeseries_date'), 'pnl_timeseries', ['date'], unique=False)
    op.create_index(op.f('ix_pnl_timeseries_id'), 'pnl_timeseries', ['id'], unique=False)
    op.create_index('ix_pnl_account_date', 'pnl_timeseries', ['account_id', 'date'], unique=True)
    
    op.create_table('risk_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('as_of_date', sa.DateTime(), nullable=False),
    sa.Column('var_historical', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('var_parametric', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('var_alpha', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('var_lookback_days', sa.Integer(), nullable=True),
    sa.Column('portfolio_volatility', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('sharpe_ratio', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('largest_position_pct', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('num_positions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_metrics_account_id'), 'risk_metrics', ['account_id'], unique=False)
    op.create_index(op.f('ix_risk_metrics_as_of_date'), 'risk_metrics', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_risk_metrics_id'), 'risk_metrics', ['id'], unique=False)
    op.create_index('ix_risk_metrics_account_date', 'risk_metrics', ['account_id', 'as_of_date'], unique=False)
    
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('as_of_date', sa.DateTime(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('data_blob', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_account_id'), 'reports', ['account_id'], unique=False)
    op.create_index(op.f('ix_reports_as_of_date'), 'reports', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_as_of_date'), table_name='reports')
    op.drop_index(op.f('ix_reports_account_id'), table_name='reports')
    op.drop_table('reports')
    
    op.drop_index('ix_risk_metrics_account_date', table_name='risk_metrics')
    op.drop_index(op.f('ix_risk_metrics_id'), table_name='risk_metrics')
    op.drop_index(op.f('ix_risk_metrics_as_of_date'), table_name='risk_metrics')
    op.drop_index(op.f('ix_risk_metrics_account_id'), table_name='risk_metrics')
    op.drop_table('risk_metrics')
    
    op.drop_index('ix_pnl_account_date', table_name='pnl_timeseries')
    op.drop_index(op.f('ix_pnl_timeseries_id'), table_name='pnl_timeseries')
    op.drop_index(op.f('ix_pnl_timeseries_date'), table_name='pnl_timeseries')
    op.drop_index(op.f('ix_pnl_timeseries_account_id'), table_name='pnl_timeseries')
    op.drop_table('pnl_timeseries')
    
    op.drop_index('ix_positions_account_instrument', table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_account_id'), table_name='positions')
    op.drop_table('positions')
    
    op.drop_index(op.f('ix_trades_timestamp'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_account_id'), table_name='trades')
    op.drop_table('trades')
    
    op.drop_index('ix_prices_instrument_timestamp', table_name='prices')
    op.drop_index(op.f('ix_prices_timestamp'), table_name='prices')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_table('prices')
    
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_id'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###